name: YetkililerUI
author: xRookieFight
version: 0.0.1
main: xRookieFight\Yetkililer
api: 3.15.0
description: Yetkililere bakmak için yapılmış plugindir.
commands:
  yetkililer:
    description: Yetkililer Menüsü. - xRookieFight
    aliases: ["kadro"]
